### PR TITLE
Add chatQnA UI manifest

### PR DESCRIPTION
**Pull request by WenjiaoYue**
## Description

Add chatQnA UI manifest.

## Issues

https://github.com/opea-project/GenAIExamples/issues/657

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

no

## Tests
kubectl apply -f chatqna.yaml

### CODE REVIEW

**Review by chensuyue — APPROVED** [review]

**Review by lvliang-intel — APPROVED** [review]

**Comment by lianhao** [comment]
I believe the ui+nginx doesn't work on k8s unless you make some tweak during installation, @Ruoyu-y have tested it, and may have more insights into it.

**Comment by Ruoyu-y** [comment]
From the PR, i could see the UI deployment is done with NO environment variable set for backend service and data prep. Although nginx is up and running as a reverse proxy for the backend services, its ip address and port is not consumed by the UI. From my point of view, UI is not able to connect to the backend services for serving. @WenjiaoYue Any comments?

**Comment by WenjiaoYue** [comment]
No, the .env configuration file of the UI has been changed to a relative path. When nginx proxies requests to the backend server, it will automatically add the configured backend URL to these relative paths. For example, if the frontend sends a request to /v1/chatqna, nginx will forward it to http://backend_server/v1/chatqna. I have tested it before submitting the PR, and the function is fine.
image
image
image

**Comment by Ruoyu-y** [comment]
> No, the UI's .env configuration file has been updated to use relative paths. When Nginx proxies requests to the backend server, it automatically appends the configured backend URL to these relative paths. For example, if the frontend sends a request to /v1/chatqna, Nginx will forward it to http://backend_server/v1/chatqna. I have already tested this before submitting the PR, and it works fine. @Ruoyu-y @lianhao image image image

Got it. So this relative path will be automatically completed with nginx ip and port? Or the UI can directly call to these relative path which would be captured by nginx? (Can you help explain a bit?) Is this approach only work for svelte or it can also work for react?

**Comment by WenjiaoYue** [comment]
> > No, the UI's .env configuration file has been updated to use relative paths. When Nginx proxies requests to the backend server, it automatically appends the configured backend URL to these relative paths. For example, if the frontend sends a request to /v1/chatqna, Nginx will forward it to http://backend_server/v1/chatqna. I have already tested this before submitting the PR, and it works fine. @Ruoyu-y @lianhao image image image
> 
> Got it. So this relative path will be automatically completed with nginx ip and port? Or the UI can directly call to these relative path which would be captured by nginx? (Can you help explain a bit?) Is this approach only work for svelte or it can also work for react?

The .env file defines relative paths, and Nginx uses these paths to proxy requests to the specified backend URL. Nginx identifies and forwards requests through the location and proxy_pass directives, which automatically append the relative path to the backend URL. Only work for svelte, while React is developed by other developers, who can refer to this for modifications.

**Pull request merged**
