### PR TITLE
[Doc]Add a micro/mega service WorkFlow for DocSum 

### PR DESCRIPTION
**Pull request by louie-tsai**
added a micro/megaservice workflow for Doc Sum

## Description

Need a workflow how we build DocSum via mega and micro service

## Issues

n/a

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [x] Others (enhancement, documentation, validation, etc.)

## Dependencies

NA

## Tests

NA

### CODE REVIEW

**Review by Spycsh — APPROVED** [review]

**Comment by alexsin368** [comment]
Looks good.

**Comment by chensuyue** [comment]
`pre-commit.ci ` is not able to fix your branch (I think it's because `intel-ai-tce` org reject it), please run the test locally and push again. 
steps: 
```
pip install pre-commit
pre-commit install
git commit -s -m "fix format issue"
```

**Comment by louie-tsai** [comment]
> `pre-commit.ci ` is not able to fix your branch (I think it's because `intel-ai-tce` org reject it), please run the test locally and push again. steps:
> 
> ```
> pip install pre-commit
> pre-commit install
> git commit -s -m "fix format issue"
> ```

thanks. I used below instruction instead.
```
pre-commit run --all-files
```

one quick question, should I add any github user to the forked repo to avoid this issue in the future?

**Comment by louie-tsai** [comment]
> Looks good.

please help to approve it if it looks good to you.

**Review by yinghu5 — APPROVED** [review]
approved it

**Pull request merged**
