### PR TITLE
Refactor Translation Example

### PR DESCRIPTION
**Pull request by zehao-intel**
## Description

Refactor Translation example to the new structure

## Issues

`n/a`

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [x] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

`n/a`

## Tests

`n/a`

### CODE REVIEW

**Review by daisy-ycguo — COMMENTED** [review]
Please move "Translation" from not supported case line to the upper case line in this file: [.github/workflows/scripts/build_push.sh](https://github.com/opea-project/GenAIExamples/blob/main/.github/workflows/scripts/build_push.sh#L56). The manifest e2e test will pass. Thank you.

**Comment by zehao-intel** [comment]
> Please move "Translation" from not supported case line to the upper case line in this file: [.github/workflows/scripts/build_push.sh](https://github.com/opea-project/GenAIExamples/blob/main/.github/workflows/scripts/build_push.sh#L56). The manifest e2e test will pass. Thank you.

Hi, @daisy-ycguo . Thanks for reminding me. I have made the modification now.
Besides, I notice that "SearchQnA" is both in the not-supported-case line and the upper-case line. Do you know if it is expected?

**Comment by daisy-ycguo** [comment]
> > Please move "Translation" from not supported case line to the upper case line in this file: [.github/workflows/scripts/build_push.sh](https://github.com/opea-project/GenAIExamples/blob/main/.github/workflows/scripts/build_push.sh#L56). The manifest e2e test will pass. Thank you.
> 
> Hi, @daisy-ycguo . Thanks for reminding me. I have made the modification now. Besides, I notice that "SearchQnA" is both in the not-supported-case line and the upper-case line. Do you know if it is expected?

It is not expected. I might miss this workload. Please help to add it to the right line. Thank you.

**Comment by zehao-intel** [comment]
> > > Please move "Translation" from not supported case line to the upper case line in this file: [.github/workflows/scripts/build_push.sh](https://github.com/opea-project/GenAIExamples/blob/main/.github/workflows/scripts/build_push.sh#L56). The manifest e2e test will pass. Thank you.
> > 
> > 
> > Hi, @daisy-ycguo . Thanks for reminding me. I have made the modification now. Besides, I notice that "SearchQnA" is both in the not-supported-case line and the upper-case line. Do you know if it is expected?
> 
> It is not expected. I might miss this workload. Please help to add it to the right line. Thank you.

Sure, do you want me to remove it from the not-supported-case line or the upper-case line?

**Review by WenjiaoYue — APPROVED** [review]

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
