### PR TITLE
[CodeTrans]Update README.md for docker build issue and UI

### PR DESCRIPTION
**Pull request by louie-tsai**
## Description

fix docker build issues and add UI section

## Issues

N/A (JIRA Gen-2)

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

NA

## Tests

Test on IDC Gaudi2 VM instance

### CODE REVIEW

**Review by letonghan — APPROVED** [review]

**Review by chensuyue — APPROVED** [review]

**Comment by chensuyue** [comment]
pre-commit.ci not able to push the format fix commit to your branch, so it failed.

**Comment by chensuyue** [comment]
You can fix the CI issue in your local machine, 
image

**Comment by louie-tsai** [comment]
> You can fix the CI issue in your local machine, image

done. Let me know any modification needed.
image

**Comment by chensuyue** [comment]
> > You can fix the CI issue in your local machine, image
> 
> done. Let me know any modification needed. image

After the issue has been fixed, you have to push the fix commit into this PR. I didn't see any new commit, do you mean no file has been updated?

**Comment by chensuyue** [comment]
image
The failure due to the prettier scan, It seems in your local place the scan failed due to the Node version is not enough.

**Comment by chensuyue** [comment]
image
pre-commit.ci - pr  are not able to push into this org, but if you submit PR from a personal forked Repo, the auto fix will work.

**Pull request merged**
