### PR TITLE
Update Productivity README.md for workflow

### PR DESCRIPTION
**Pull request by louie-tsai**
## Description

Added a workflow for Productivity following what ChatQnA has. [ChatQnA flow](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#architecture-and-deploy-details)

## Issues

 `n/a`.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

na

## Diagram

```mermaid
---
config:
  flowchart:
    nodeSpacing: 400
    rankSpacing: 100
    curve: linear
  themeVariables:
    fontSize: 50px
---
flowchart LR
    %% Colors %%
    classDef blue fill:#ADD8E6,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef orange fill:#FBAA60,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef orchid fill:#C26DBC,stroke:#ADD8E6,stroke-width:2px,fill-opacity:0.5
    classDef invisible fill:transparent,stroke:transparent;
    style ChatQnA-MegaService stroke:#000000

    %% Subgraphs %%
    subgraph ChatQnA-MegaService["ChatQnA MegaService "]
        direction LR
        EM([Embedding MicroService]):::blue
        RET([Retrieval MicroService]):::blue
        RER([Rerank MicroService]):::blue
        LLM([LLM MicroService]):::blue
    end
    subgraph DocSum-MegaService["DocSum MegaService "]
        direction LR
        LLM_D([LLM MicroService]):::blue
    end
    subgraph CodeGen-MegaService["CodeGen MegaService "]
        direction LR
        LLM_CG([LLM MicroService]):::blue
    end
    subgraph FaqGen-MegaService["FaqGen MegaService "]
        direction LR
        LLM_F([LLM MicroService]):::blue
    end
    subgraph UserInterface[" User Interface "]
        direction LR
        a([User Input Query]):::orchid
        Ingest([Ingest data]):::orchid
        UI([UI server<br>]):::orchid
    end



    TEI_RER{{Reranking service<br>}}
    TEI_EM{{Embedding service <br>}}
    VDB{{Vector DB<br><br>}}
    R_RET{{Retriever service <br>}}
    DP([Data Preparation MicroService]):::blue
    LLM_gen_C{{LLM Service <br>}}
    GW_C([ChatQnA GateWay<br>]):::orange
    LLM_gen_D{{LLM Service <br>}}
    GW_D([DocSum GateWay<br>]):::orange
    LLM_gen_CG{{LLM Service <br>}}
    GW_CG([CodeGen GateWay<br>]):::orange
    LLM_gen_F{{LLM Service <br>}}
    GW_F([FaqGen GateWay<br>]):::orange
    PR([Prompt Registry MicroService]):::blue
    CH([Chat History MicroService]):::blue
    MDB{{Mongo DB<br><br>}}


    %% Data Preparation flow
    %% Ingest data flow
    direction LR
    Ingest[Ingest data] --> UI
    UI --> DP
    DP <-.-> TEI_EM

    %% Questions interaction
    direction LR
    a[User Input Query] --> UI
    UI --> GW_C
    GW_C <==> ChatQnA-MegaService
    EM ==> RET
    RET ==> RER
    RER ==> LLM


    %% Embedding service flow
    direction LR
    EM <-.-> TEI_EM
    RET <-.-> R_RET
    RER <-.-> TEI_RER
    LLM <-.-> LLM_gen_C

    direction LR
    %% Vector DB interaction
    R_RET <-.-> VDB
    DP <-.-> VDB

    %% Questions interaction
    direction LR
    UI --> GW_D
    GW_D <==> DocSum-MegaService


    %% Embedding service flow
    direction LR
    LLM_D <-.-> LLM_gen_D

    %% Questions interaction
    direction LR
    UI --> GW_CG
    GW_CG <==> CodeGen-MegaService


    %% Embedding service flow
    direction LR
    LLM_CG <-.-> LLM_gen_CG

    %% Questions interaction
    direction LR
    UI --> GW_F
    GW_F <==> FaqGen-MegaService


    %% Embedding service flow
    direction LR
    LLM_F <-.-> LLM_gen_F

    %% Questions interaction
    direction LR
    UI --> PR
  
    %% Embedding service flow
    direction LR
    PR <-.-> MDB

    %% Questions interaction
    direction LR
    UI --> CH
  
    %% Embedding service flow
    direction LR
    CH <-.-> MDB

```

### CODE REVIEW

**Comment by hteeyeoh** [comment]
One minor suggestion, right now prompt registry and chat-history service are only work with chatqna micoservice in ProductivitySuite. Maybe we can draw/link these two services to chatqna to give more precise flow to public.

**Comment by louie-tsai** [comment]
> Collaborator

For the workflow wise, UI server indeed connects with chathistory and prompt registry directly, so not sure how we make the flow between chatqna and those microservices.

However, put some comments on the flow among UI and those megaservice and microservices to explain the connections.
image
image

Hope it helps.

**Comment by hteeyeoh** [comment]
> > Collaborator
> 
> For the workflow wise, UI server indeed connects with chathistory and prompt registry directly, so not sure how we make the flow between chatqna and those microservices.
> 
> However, put some comments on the flow among UI and those megaservice and microservices to explain the connections. image image
> 
> Hope it helps.

looks good to me...

**Review by hteeyeoh — APPROVED** [review]

**Comment by xiguiw** [comment]
When I first look at the flow without knowing you conversation, I was confused by the flow.
Why first step (1) is get response instead of sending request?
Why there two `step 2`? 

This step and number assumed you focus on 'chathistory and prompt registry' only.
Maybe it is clearer to me by explaining them in words instead of adding the step in the flow.

**Comment by hteeyeoh** [comment]
> When I first look at the flow without knowing you conversation, I was confused by the flow. Why first step (1) is get response instead of sending request? Why there two `step 2`?
> 
> This step and number assumed you focus on 'chathistory and prompt registry' only. Maybe it is clearer to me by explaining them in words instead of adding the step in the flow.

I think removing the steps in grey from flow and putting explanation of them in word would be more clearer to public user. I agree with that

**Comment by louie-tsai** [comment]
> prompt registry and chat-history service are only work with chatqna micoservice

addressed accordingly.

**Review by xiguiw — APPROVED** [review]

**Review by hteeyeoh — APPROVED** [review]

**Pull request merged**
