### PR TITLE
Update README.md to notify two gaudi cards needed

### PR DESCRIPTION
**Pull request by louie-tsai**
ChatQnA needs two gaudi cards. put a note to inform users.

## Description

ChatQnA needs two gaudi cards. put a note to inform users.

## Issues

N/A

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

NA

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
@louie-tsai Thank you for your PR. Yet I don't think ChatQnA requires at least 2 gaudi card, because I've run ChatQnA successfully using 1 Gaudi card. I don't agree with your changes.

**Comment by louie-tsai** [comment]
> @louie-tsai Thank you for your PR. Yet I don't think ChatQnA requires at least 2 gaudi cards, because I've run ChatQnA successfully using 1 Gaudi card. I don't agree with your changes.

Hi 
I used 1 card VM instance from IDC, and tgi-service didn't run successfully in that IDC VM.
image

While I tried to restart it with "docker compose -f docker_compose.yaml up tgi-service", I saw below issue.
image


However, everything works fine if I used 8 cards IDC instance.

**Comment by louie-tsai** [comment]
> > @louie-tsai Thank you for your PR. Yet I don't think ChatQnA requires at least 2 gaudi cards, because I've run ChatQnA successfully using 1 Gaudi card. I don't agree with your changes.
> 
> @daisy-ycguo Hi I used 1 card VM instance from IDC, and tgi-service didn't run successfully in that IDC VM. image
> 
> While I tried to restart it with "docker compose -f docker_compose.yaml up tgi-service", I saw below issue. image
> 
> However, everything works fine if I used 8 cards IDC instance.

once I changed tei-embedding-server from gaudi to cpu, it works.
image

**Comment by kevinintel** [comment]
@louie, please fix DCO

**Comment by louie-tsai** [comment]
> @louie, please fix DCO

@kevinintel 
thanks for reminding. addressed it accordingly.

**Review by chensuyue — APPROVED** [review]

**Review by kevinintel — APPROVED** [review]

**Comment by kevinintel** [comment]
looks like it has conflicts

**Pull request merged**
