### PR TITLE
[DocIndexRetriever] enable the without-rerank flavor

### PR DESCRIPTION
**Pull request by gavinlichn**
## Description

Enable the without-rerank flavor for DocIndexRetriever
Without-rerank flavor for customers that design to handle all documents by LLM and require high performance of DocRetriever

## Issues

n/a
## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by minmin-intel** [comment]
@gavinlichn Please add unit tests for DocIndexRetriever without reranker in the tests folder

**Comment by gavinlichn** [comment]
> @gavinlichn Please add unit tests for DocIndexRetriever without reranker in test_compose_on_gaudi.sh and test_compose_on_xeon.sh

Submitted new patch for test script test_compose_on_xeon_without_rerank.sh

**Comment by minmin-intel** [comment]
> > @gavinlichn Please add unit tests for DocIndexRetriever without reranker in test_compose_on_gaudi.sh and test_compose_on_xeon.sh
> 
> Submitted new patch for test script test_compose_on_xeon_without_rerank.sh

UT needs to be inside test_compose_on_xeon.sh to be intrigued by CI.

**Comment by gavinlichn** [comment]
> > > @gavinlichn Please add unit tests for DocIndexRetriever without reranker in test_compose_on_gaudi.sh and test_compose_on_xeon.sh
> > 
> > 
> > Submitted new patch for test script test_compose_on_xeon_without_rerank.sh
> 
> UT needs to be inside test_compose_on_xeon.sh to be intrigued by CI.

renamed the script, UT triggered by CI and passed now

**Comment by gavinlichn** [comment]
@minmin-intel @lvliang-intel  Please help to review this PR, it passed all test and pending for review.

**Review by minmin-intel — APPROVED** [review]

**Review by lvliang-intel — APPROVED** [review]

**Pull request merged**
