### PR TITLE
Add VideoRAGQnA as MMRAG usecase in Example

### PR DESCRIPTION
**Pull request by BaoHuiling**
## Description

Add VideoRAGQnA as MMRAG usecase in Example 

## Issues

https://github.com/opea-project/GenAIExamples/issues/358

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)
- [ ] Others (enhancement, documentation, validation, etc.)

## Dependencies

streamlit

## Tests
VideoRAGQnA/tests/test_compose_on_xeon.sh

### CODE REVIEW

**Comment by BaoHuiling** [comment]
The test is WIP, and it will only work when https://github.com/opea-project/GenAIComps/pull/621 and https://github.com/opea-project/GenAIComps/pull/603 is merged. please hold
@lvliang-intel @chensuyue  could you help to tag the PR milestone for 1.0?

**Review by lvliang-intel — APPROVED** [review]

**Comment by lvliang-intel** [comment]
@BaoHuiling,
About the CI issue, you should put the 'tests' directory in the ‘MultiModalRAGQnA’.
Why do you set two level folders for this example?

image

**Comment by BaoHuiling** [comment]
> @BaoHuiling, About the CI issue, you should put the 'tests' directory in the ‘MultiModalRAGQnA’. Why do you set two level folders for this example?
> 
> image

Hi Liang, thanks for comment, because we are contributing 2 use cases for the MMRAG, see https://github.com/opea-project/GenAIExamples/issues/358#issuecomment-2333005982

I will move the test to upper folder.

**Comment by BaoHuiling** [comment]
Waiting for https://github.com/opea-project/GenAIComps/pull/621/files merged

**Comment by BaoHuiling** [comment]
@lvliang-intel @kevinintel @XuhuiRen @Spycsh Hi all, this PR finished the file strcture update and passed all CI test, could you help to review and merge it? Thanks a lot

**Comment by BaoHuiling** [comment]
@yinghu5 @chensuyue Add more reviewers🙂

**Review by kevinintel — APPROVED** [review]

**Pull request merged**
