### PR TITLE
Updated ReadMe for ChatQnA

### PR DESCRIPTION
**Pull request by srinarayan-srikanthan**
## Description

Updated the readme for chatqna with path fix and added cd instructions for reproducibility. 

## Issues

PR # 231 and 232

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds new functionality)
- [ ] Breaking change (fix or feature that would break existing design and interface)

## Dependencies

N/A

## Tests

Describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by srinarayan-srikanthan** [comment]
I can create similar PR for other examples once this is approved.

**Comment by dcmiddle** [comment]
I think I have all the path fixes here: https://github.com/opea-project/GenAIExamples/pull/260

**Comment by srinarayan-srikanthan** [comment]
Yes i see you have covered it in that PR, one thing that i also added is cd instructions to make sure copy paste instructions work instead of users not having to worry about the current directories.

**Review by lvliang-intel — APPROVED** [review]

**Review by kevinintel — APPROVED** [review]

**Comment by kevinintel** [comment]
Should we merge this PR or https://github.com/opea-project/GenAIExamples/pull/260 ?

**Pull request merged**
