### PR TITLE
Detect dangerous command

### PR DESCRIPTION
**Pull request by VincyZhang**
## Description

To detect dangerous command in shell/python scripts to avoid harmful impact on test servers

## Issues

Some dangerous commands are brought by user's scripts which may have impact on test servers

## Type of change

enhancement for CI

## Dependencies

None

## Tests

CI

### CODE REVIEW

**Review by lvliang-intel — APPROVED** [review]

**Comment by lvliang-intel** [comment]
@VincyZhang,

Welcome back :-)

**Comment by VincyZhang** [comment]
Test results can be found in: https://github.com/VincyZhang/GenAIExamples/actions/workflows/pr-code-scan.yml

**Comment by chensuyue** [comment]
Let's create a common action in https://github.com/opea-project/Validation, which can be referred by all the OPEA projects.

**Comment by VincyZhang** [comment]
test pass: https://github.com/opea-project/GenAIExamples/actions/runs/11968667505/job/33368353073?pr=1179

**Comment by VincyZhang** [comment]
Validation PR: https://github.com/opea-project/Validation/pull/44

**Review by chensuyue — APPROVED** [review]

**Pull request merged**
