### PR TITLE
Add Session History Feature for the Video RAG Chat Interface

### PR DESCRIPTION
**Pull request by bashirmoham**
## Description

This pull request adds a session history feature to the get_formatted_prompt function. The changes include updating the function to accept and utilize the history parameter, ensuring that the user's previous chat history is incorporated into the prompt formatting process.

## Changes Made

  - Added get_history function to retrieve the last three messages from the session state
  - Added the `history` parameter to the get_formatted_prompt function signature.
  - Assigned the `history` variable within the template rendering process to maintain correct scope and functionality.
  - Included placeholders for scene description, user's previous chat history, and user's question.
  - Added rules for the assistant to follow while answering questions based on the provided scene description and history.

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds new functionality)

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Tested and now showing the history.

### CODE REVIEW

**Comment by lvliang-intel** [comment]
@bashirmoham,

could you please fix the pre-commit issues?

image

**Comment by lvliang-intel** [comment]
and also code scan issue:

image

**Comment by chensuyue** [comment]
Please do not upstream a list of video in the repo.   
BTW, @bashirmoham do you still want to merge this PR, it pending for a long time, if not, we will close it.

**Comment by bashirmoham** [comment]
Please close it.
Thanks

**Comment by xiguiw** [comment]
> Please close it. Thanks From: chen, suyue ***@***.***> Sent: Wednesday, November 13, 2024 7:44 PM To: opea-project/GenAIExamples ***@***.***> Cc: Mohammed, Bashir ***@***.***>; Mention ***@***.***> Subject: Re: [opea-project/GenAIExamples] Add Session History Feature for the Video RAG Chat Interface (PR #253) Please do not upstream a list of video in the repo. BTW, @bashirmoham<https://github.com/bashirmoham> do 

Close it.

**Pull request closed without merging**
