### PR TITLE
ChatQnA - Add Terraform and Ansible Modules information

### PR DESCRIPTION
**Pull request by lucasmelogithub**
## Description

- Intel has developed Terraform and Ansible Modules. 

- These have now been enhanced to provision Xeon based Cloud Instances and to automate deployment of OPEA ChatQnA 

## Issues

Addresses: #560 #962 #963 

## Type of change

List the type of change like below. Please delete options that are not relevant.

- [ x ] Documentation

## Dependencies

List the newly introduced 3rd party dependency if exists.

## Tests

Validated deployments following Terraform/Ansible Modules README.md

### CODE REVIEW

**Comment by mkbhanda** [comment]
Please publish your scripts in the OPEA repo. That way OPEA is self contained and the launch scripts are readily available through just a purview of the repository, beyond embedded in a readme file.  Do consider naming the script OPEA single node VM or something to that effect and add some text perhaps that suggests number of vCPUs, disk size based on model or example pipeline, so its generic and can be used for more than ChatQnA, re-use being my intent. Also anticipating these scripts changing a bit as other handware vendors join the effort.

**Comment by lucasmelogithub** [comment]
> Please publish your scripts in the OPEA repo. That way OPEA is self contained and the launch scripts are readily available through just a purview of the repository, beyond embedded in a readme file. Do consider naming the script OPEA single node VM or something to that effect and add some text perhaps that suggests number of vCPUs, disk size based on model or example pipeline, so its generic and can be used for more than ChatQnA, re-use being my intent. Also anticipating these scripts changing a bit as other handware vendors join the effort.

Feedback received, I'm thinking through it and will propose a change.

**Comment by lucasmelogithub** [comment]
Malini and I had a conversation. 
I went over the existing Terraform Modules that have been used beyond OPEA and the Ansible playbooks.
The agreement is 
- For now, leave links on each Use Case in README, decide on future later. 
- We will revisit as needed, the Terraform Examples and Ansible Playbooks can be moved to OPEA if we think that is a better design long term.

In addition, we will add generic VM examples to the GenInfra repository with another PR.

**Review by mkbhanda — APPROVED** [review]
LGTM

**Review by mkbhanda — APPROVED** [review]
LGTM

**Review by ashahba — APPROVED** [review]
LGTM!

**Pull request merged**
